### ISSUE TITLE
Changing `xcp.accessor` API to explicitly specify text or binary mode

### ISSUE THREAD

**Issue by ydirson** [xenserver/python-libs#19]
Context: commit "WIP xcp.repository: switch from ConfigParser to configparser" in #17 (current shortcut: https://github.com/ydirson/xenserver-python-libs/commit/6667fef9284b6f501c41c096c790ad298094c101).  When adding python3 compatibility, we see some `Accessor` implementations (e.g. FileAccessor) provide a text stream, while others (e.g. HTTPAccessor) provide a binary
stream.  This is a problem for code written to be compatible with arbitrary `Accessor` implementations, as demonstrated in additional unit tests in commits [WIP test_accessor: check for I/O on binary files](https://github.com/ydirson/xenserver-python-libs/commit/bb895037d68d0f09a7b3b651f89e17beabba1046) and [WIP test_accessor: write into copy file as binary](https://github.com/ydirson/xenserver-python-libs/commit/e4fcc95268284a26c5a8e659e4be639824c32f24).

To be in line with file-opening conventions, `Accessor.openAddress()` should be made to accept a `mode` argument so client code can get what it expects without a need for hacks such as illustrated above.  To make sure not-yet-reviewed/converted client code is caught red-handed, I would rather add this parameter as mandatory.

Identified client code to be reviewed/adjusted in lockstep include:
- XAPI plugin `prepare_host_upgrade` (not in any public repo yet ?)
- `xcp.repository` (internal dependency, not a problem)

Additionally, https://github.com/xenserver/host-installer contains a forked version of this code in `repository.py` (itself an advanced fork of `xcp.repository`).

**Comment by kc284** [comment]
If the script changes and the previous one is not working we will have to repackage the hotfix ISO shipped with XenCenter.

**Comment by bernhardkaindl** [comment]
In the end, this was the solution for it:

To support getting text where bytes-based IO (e.g. socket) needs to be wrapped, the only way to implement it properly is a @contextmanager that yields a `io.TextIOWrapper` to the caller and cleans up after the context is left.

It is merged with and tested with all relevant Accessor types in #76, here is a link to the implementation:

https://github.com/xenserver/python-libs/commit/0d3d93b609dbfc75dff7801339371c3c5ac4e82d#diff-9491984f26a75ac2cde097f20f7072e360355d7fa7cad473909a276970aec00bR79
